### ISSUE TITLE
Can't dataize `while` loop

### ISSUE THREAD

**Issue by volodya-lombrozo** [objectionary/eo#1698]
I have the next `eo` program:
```eo
+alias org.eolang.txt.sprintf
+alias org.eolang.io.stdout

[] > example
  cage 0 > index
  seq > @
    while.
      index.lt 10
      [i]
        index.write (index.plus 1)
    stdout
      sprintf
        "%s"
        index
    TRUE
```

Expected: Program compiles successfully.
Actual: I get the next exception:
```
EOorg.EOeolang.EOstringν137="Error at "bool.while.f" attribute; caused by The object is at the line #9, position #6; caused by ExUnset: Error at "EOexample$EOt1$EOt0$EOa1#Δ" attribute; caused by ExUnset: Can't get(), attribute "Δ" is absent among other 3 attrs (ρ, i, σ) and φ is absent"SF
```

**Comment by Graur** [comment]
@volodya-lombrozo Looks like it should be `index.write (index.plus 1) > @`

**Comment by volodya-lombrozo** [comment]
@Graur With that program:
```eo
+alias org.eolang.txt.sprintf
+alias org.eolang.io.stdout

[] > example
  cage 0 > index
  seq > @
    while.
      index.lt 10
      [i]
        index.write (index.plus 1) > @
    stdout
      sprintf
        "%s"
        index
    TRUE
``` 

I get the next exception:
```bash
EO version is 0.28.17
EO objects registered in /Users/lombrozo/Workspace/EOlang/learning/while_simple/.eoc/eo-foreign.json
EO version is 0.28.17
EO program assembled in /Users/lombrozo/Workspace/EOlang/learning/while_simple/.eoc
EO version is 0.28.17
Java sources generated in /Users/lombrozo/Workspace/EOlang/learning/while_simple/.eoc/generated-sources
EO version is 0.28.17
Java .class files compiled into /Users/lombrozo/Workspace/EOlang/learning/while_simple/.eoc
EO version is 0.28.17
Executable JAR created at /Users/lombrozo/Workspace/EOlang/learning/while_simple/.eoc/eoc.jar
EOorg.EOeolang.EOstringν166="Unexpected error 'null' of type StackOverflowError; caused by "SF
```

**Comment by mximp** [comment]
@volodya-lombrozo would it work if you switch `cage` to `memory`?

**Comment by volodya-lombrozo** [comment]
@mximp Yes, the next program prints `11` (why?):
```eo
+alias org.eolang.txt.sprintf
+alias org.eolang.io.stdout

[] > example
  memory 0 > index
  seq > @
    while.
      index.lt 10
      [i]
        index.write (index.plus 1) > @
    stdout
      sprintf
        "%s"
        index
    TRUE
```
Magic...

**Comment by mximp** [comment]
@volodya-lombrozo The reasoning behind the value `11` you can find in this [blog post](https://news.eolang.org/2022-12-22-declarative-while.html).  
As for `cage` vs `memory` result: I believe that's due to the difference in what is written - the former writes the object you pass and the latter writes the result. I'd say for complete explanation these two cases need to be debugged carefully :)

**Comment by yegor256** [comment]
@volodya-lombrozo `cage` save an object inside, while `memory` dataizes the object first and then saves the bytes. The `cage` is lazy, while the `memory` is eager.

**Comment by volodya-lombrozo** [comment]
@yegor256 It still isn't clear why the first code sample throws `StackOverflowError ` , even if it's lazy, we will get the next code:
```
((((((((((0.plus 1).plus 1).plus 1).plus 1).plus 1).plus 1).plus 1).plus 1).plus 1).plus 1)
```
only 10 objects. Please, correct me if I'm wrong.

**Comment by Graur** [comment]
@volodya-lombrozo As far as I understand, it will be always `(index.plus 1)` object in cage and endless loop since `index` object didn't updated.

**Comment by volodya-lombrozo** [comment]
@Graur Sorry, I still don't understand, let's imagine iterations:

```
1. index == (0.plus 1)                    # no dataization here
2. index ==  ((0.plus 1).plus 1)          # no dataization here
3. index ==  (((0.plus 1).plus 1).plus 1) # no dataization here
```

Then, when I call
```
stdout
      sprintf
        "%s"
        index.  #dataization!
```
The dataization should happen right here. Am I right? I don't see "endless loop" here

**Comment by volodya-lombrozo** [comment]
@mximp It doesn't help.
```eo
+alias org.eolang.txt.sprintf
+alias org.eolang.io.stdout

[] > example
  cage 0 > index
  seq > @
    index.write 0
    while.
      index.lt 10
      [i]
        index.write (index.plus 1) > @
    stdout
      sprintf
        "%s"
        index
    TRUE
```
Result:
```sh
EO version is 0.28.17
EO objects registered in /Users/lombrozo/Workspace/EOlang/learning/while_simple/.eoc/eo-foreign.json
EO version is 0.28.17
EO program assembled in /Users/lombrozo/Workspace/EOlang/learning/while_simple/.eoc
EO version is 0.28.17
Java sources generated in /Users/lombrozo/Workspace/EOlang/learning/while_simple/.eoc/generated-sources
EO version is 0.28.17
Java .class files compiled into /Users/lombrozo/Workspace/EOlang/learning/while_simple/.eoc
EO version is 0.28.17
Executable JAR created at /Users/lombrozo/Workspace/EOlang/learning/while_simple/.eoc/eoc.jar
EOorg.EOeolang.EOstringν178="Unexpected error 'null' of type StackOverflowError; caused by "SF
```

**Comment by volodya-lombrozo** [comment]
@yegor256 Apparently we have a bug here.

**Comment by mximp** [comment]
@volodya-lombrozo is this still valid bug?

**Comment by yegor256** [comment]
@volodya-lombrozo stack overflow is a known problem, which can only be fixed by increasing the size of the stack. Please, try to increase it and run again.

**Comment by yegor256** [comment]
@Graur I believe, the best fix for this type of a problem would be to catch `StackOverflowError` at the highest level and add rethrow it with a better message, like "Please, increase the size of the stack..."

**Comment by volodya-lombrozo** [comment]
@yegor256 I'm afraid it is problem with `while` loop, not with `StackOverflowError `

**Comment by yegor256** [comment]
@volodya-lombrozo increasing the size of the stack doesn't help?

**Comment by volodya-lombrozo** [comment]
@yegor256 No, it's a problem with the `while` loop.

I've tried to compile with the newest version of eo-maven-plugin and still get an error:
```
EOorg.EOeolang.EOstringν200="Unexpected error 'null' of type StackOverflowError; caused by "SF
```

**Comment by maxonfjvipon** [comment]
@volodya-lombrozo It's not a problem with `while` or `cage`, there's no problem at all, just a feature of work of the `cage`.
First of all, since we [changed](https://github.com/objectionary/eo/pull/2332) `cage` I rewrite your example and simplify it without using `while`
```
[] > example
  cage > cge
    plus.
      1
      1
  seq > @
    cge.write
      plus.
        cge
        2
    cge
```

If we try to dataize `example` we will get `StackOverflow`. Why:

1. We initialize `cage` with not dataized `1.plus 1`. At this step `1.plus 1` is set to `cge.enclosure` attribute
2. Then we write `cge.plus 2` to `cge` without any dataization. At this step `cge.enclosure` attribute is rewritten with not dataized `cge.plus 2`
3. Then we dataize `cge` -> it goes to `cge.enclosure` -> tries to dataize it -> `cge.enclosure` contains not dataized `cge.plus 2`(see step 2) -> then it tries to dataize `cge` again -> `cge.enclosure` -> `cge.plus 2` -> `cge` -> `cge.enclosure` -> ... -> Hello StackOverflow

The conclusion that can be made here - you can't/should not even try to write to the `cage` an object which was obtained by any manipulation with the same `cage`.

I don't know how we can test it but I believe we should somehow document it.
@yegor256 @volodya-lombrozo @Graur any suggestions?

**Comment by maxonfjvipon** [comment]
@volodya-lombrozo the next code works:
```
[] > cage-in-while
  cage > index
    plus.
      0
      0
  seq > @
    while.
      index.lt 10
      [i]
        index.write > @
          plus.
            index'
            1
    QQ.io.stdout
      QQ.txt.sprintf
        "%s"
        index
    TRUE
```

Here you copy `index` before writing it make `index` and its copy had different `enclosure` attributes while dataization

**Comment by volodya-lombrozo** [comment]
@maxonfjvipon Thank you for the detailed explanation! It sheds light on the problem.

**Comment by 0pdd** [comment]
@volodya-lombrozo the puzzle [#2409](https://github.com/objectionary/eo/issues/2409) is still not solved.

**Comment by 0pdd** [comment]
@volodya-lombrozo the puzzle [#2836](https://github.com/objectionary/eo/issues/2836) is still not solved; solved: [#2409](https://github.com/objectionary/eo/issues/2409).

**Comment by 0pdd** [comment]
@volodya-lombrozo 3 puzzles [#2836](https://github.com/objectionary/eo/issues/2836), [#2890](https://github.com/objectionary/eo/issues/2890), [#2891](https://github.com/objectionary/eo/issues/2891) are still not solved; solved: [#2409](https://github.com/objectionary/eo/issues/2409).

**Comment by 0pdd** [comment]
@volodya-lombrozo 3 puzzles [#2836](https://github.com/objectionary/eo/issues/2836), [#2891](https://github.com/objectionary/eo/issues/2891), [#2896](https://github.com/objectionary/eo/issues/2896) are still not solved; solved: [#2409](https://github.com/objectionary/eo/issues/2409), [#2890](https://github.com/objectionary/eo/issues/2890).

**Comment by 0pdd** [comment]
@volodya-lombrozo 2 puzzles [#2891](https://github.com/objectionary/eo/issues/2891), [#2896](https://github.com/objectionary/eo/issues/2896) are still not solved; solved: [#2409](https://github.com/objectionary/eo/issues/2409), [#2836](https://github.com/objectionary/eo/issues/2836), [#2890](https://github.com/objectionary/eo/issues/2890).

**Comment by 0pdd** [comment]
@volodya-lombrozo the puzzle [#2896](https://github.com/objectionary/eo/issues/2896) is still not solved; solved: [#2409](https://github.com/objectionary/eo/issues/2409), [#2836](https://github.com/objectionary/eo/issues/2836), [#2890](https://github.com/objectionary/eo/issues/2890), [#2891](https://github.com/objectionary/eo/issues/2891).

**Comment by 0pdd** [comment]
@volodya-lombrozo the puzzle [#3181](https://github.com/objectionary/eo/issues/3181) is still not solved; solved: [#2409](https://github.com/objectionary/eo/issues/2409), [#2836](https://github.com/objectionary/eo/issues/2836), [#2890](https://github.com/objectionary/eo/issues/2890), [#2891](https://github.com/objectionary/eo/issues/2891), [#2896](https://github.com/objectionary/eo/issues/2896).

**Comment by 0pdd** [comment]
@volodya-lombrozo all 6 puzzles are solved here: [#2409](https://github.com/objectionary/eo/issues/2409), [#2836](https://github.com/objectionary/eo/issues/2836), [#2890](https://github.com/objectionary/eo/issues/2890), [#2891](https://github.com/objectionary/eo/issues/2891), [#2896](https://github.com/objectionary/eo/issues/2896), [#3181](https://github.com/objectionary/eo/issues/3181).
