### ISSUE TITLE
Naming of eo objetcs via '_' must be prohibited

### ISSUE THREAD

**Issue by levBagryansky** [objectionary/eo#1890]
I declared 2 objects:
```
[] > unusual_name
  QQ.io.stdout > @
    "unusual_name\n"

[] > unusual-name
  QQ.io.stdout > @
    "unusual-name\n"
```
and ran `mvn clean test -Dtest="*unusual_name*"`
```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running EOorg.EOeolang.EOunusual_nameTest
unusual-name
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.134 s - in EOorg.EOeolang.EOunusual_nameTest
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
```
So the program's behavior becomes unexpected. 
@yegor256 @Graur WDYT?

**Comment by yegor256** [comment]
@levBagryansky it's a bug in name mapping from XMIR to Java, should be fixed

**Comment by levBagryansky** [comment]
@Graur there is also `'.'` character. So if replace it to `'.'` then `"qwe-rty"` and `"qwe..rty"` will be the same

**Comment by Graur** [comment]
@levBagryansky Absolutely agree. But I can't find a solution without counterexample

**Comment by 0pdd** [comment]
@levBagryansky the puzzle [#2096](https://github.com/objectionary/eo/issues/2096) is still not solved.
