### ISSUE TITLE
sonar CI workflow keeps failing

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo#2251]
https://github.com/objectionary/eo/actions/workflows/sonar.yml

Let's find out what is the reason and fix

**Comment by yegor256** [comment]
@maxonfjvipon please, take a look

**Comment by yegor256** [comment]
@maxonfjvipon 

this is the recent one: https://sonarcloud.io/project/issues?resolved=false&types=BUG&sinceLeakPeriod=true&severities=BLOCKER%2CCRITICAL%2CMAJOR%2CMINOR&id=com.objectionary%3Aeo

this is the failure in CI: https://github.com/objectionary/eo/actions/runs/7721848475/job/21049050225

maybe we should add Sonar to pull request checks?

**Comment by maxonfjvipon** [comment]
@c71n93 can you take it?

**Comment by c71n93** [comment]
@maxonfjvipon yeah, I can try.

**Comment by c71n93** [comment]
That's the output of sonar analysis:
Failed conditions
 [0.0% Coverage on New Code](https://sonarcloud.io/component_measures?id=com.objectionary%3Aeo&branch=master&metric=new_coverage&view=list) (required ≥ 80%)
 [E Reliability Rating on New Code](https://sonarcloud.io/dashboard?id=com.objectionary%3Aeo&branch=master) (required ≥ A)

Issues with reliability of code is just places in code that was identified by sonar as bug. They needs to be fixed or ignored.
Issues with code coverage is sort of problem, it doesn't work properly. I created new project in sonar with my up to date fork of `objectionary/eo` for testing. I locally ran:
```
$ mvn clean install -Pjacoco
$ mvn sonar:sonar -Dsonar.token=my-sonar-token
```
and there was the result: https://sonarcloud.io/summary/overall?id=c71n93_eo%3Aeo. Code coverage is correct here.
I suppose, that coverage data is not collected in our CI, because `jacoco` is not launched [here](https://github.com/objectionary/eo/blob/master/.github/workflows/sonar.yml) before sonar analysis. Sonar requires `jacoco.xml` to show code coverage analysis.

I was trying to test my ideas in #2874, by adding "on pull-request" check to sonar workflow. But it doesn't work, because it requires `SONAR_TOKEN` (https://github.com/objectionary/eo/actions/runs/7873343508/job/21480455544?pr=2874). 

@yegor256 How can I properly enable "on pull-request" check for this workflow? I need it to debug sonar CI locally in my PR.

**Comment by yegor256** [comment]
@c71n93 try this way: https://github.com/objectionary/eo/blob/master/.github/workflows/mvn.yml#L8-L11

**Comment by c71n93** [comment]
@yegor256 In [master branch CI](https://github.com/objectionary/eo/actions/runs/7887482792/job/21522819589) token is provided by the 'SONAR_TOKEN' environment variable:
```
mvn --batch-mode -DskipTests -Dinvoker.skip verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.qualitygate.wait=true
  shell: /usr/bin/bash -e {0}
  env:
    JAVA_HOME: /opt/hostedtoolcache/Java_Zulu_jdk/20.0.2-9/x6[4](https://github.com/objectionary/eo/actions/runs/7887482792/job/21522819589#step:7:4)
    JAVA_HOME_20_X[6](https://github.com/objectionary/eo/actions/runs/7887482792/job/21522819589#step:7:6)4: /opt/hostedtoolcache/Java_Zulu_jdk/20.0.2-9/x64
    GITHUB_TOKEN: ***
    SONAR_TOKEN: ***
```

For some reasons in [CI on PR](https://github.com/objectionary/eo/actions/runs/7914383347/job/21604003667?pr=2874) the token is not provided.
```
mvn --batch-mode -DskipTests -Dinvoker.skip verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.qualitygate.wait=true
  shell: /usr/bin/bash -e {0}
  env:
    JAVA_HOME: /opt/hostedtoolcache/Java_Zulu_jdk/20.0.2-9/x6[4](https://github.com/objectionary/eo/actions/runs/7914383347/job/21604003667?pr=2874#step:7:4)
    JAVA_HOME_20_X[6](https://github.com/objectionary/eo/actions/runs/7914383347/job/21604003667?pr=2874#step:7:6)4: /opt/hostedtoolcache/Java_Zulu_jdk/20.0.2-9/x64
    GITHUB_TOKEN: ***
    SONAR_TOKEN:
```

I don't have access to this token, it is private. 

@yegor256 Do you know how to make this token accessible from CI on PR? This token needs to see analysis results in SonarCloud.

**Comment by c71n93** [comment]
@yegor256 It looks like [`secrets.SONAR_TOKEN`](https://github.com/objectionary/eo/blob/1f66aa8cd2db034850f1da823b81e9d727a03768/.github/workflows/sonar.yml#L37) is not accessible from CI on pull-request. I think [this issue from stackoverflow](https://stackoverflow.com/questions/73866908/github-actions-main-repository-secret-not-picked-up-from-pull-request-build) is related to our issue.

**Comment by yegor256** [comment]
@c71n93 I merged #2874

**Comment by yegor256** [comment]
@c71n93 let's fix these five bugs

**Comment by c71n93** [comment]
@yegor256 Okay, I will check this bugs and create issues

**Comment by c71n93** [comment]
Some useful materials about sharing secrets with workflows on PRs from forks:
[Stackoverflow (safe `pull_request_target`)](https://stackoverflow.com/questions/76952023/how-to-make-github-actions-safely-access-secrets-for-prs-created-from-forks)
[Stackoverflow (using workflow_run event on PR)](https://stackoverflow.com/questions/63343937/how-to-use-the-github-actions-workflow-run-event)

**Comment by 0pdd** [comment]
@yegor256 4 puzzles [#3298](https://github.com/objectionary/eo/issues/3298), [#3299](https://github.com/objectionary/eo/issues/3299), [#3300](https://github.com/objectionary/eo/issues/3300), [#3301](https://github.com/objectionary/eo/issues/3301) are still not solved.

**Comment by 0pdd** [comment]
@yegor256 3 puzzles [#3298](https://github.com/objectionary/eo/issues/3298), [#3299](https://github.com/objectionary/eo/issues/3299), [#3300](https://github.com/objectionary/eo/issues/3300) are still not solved; solved: [#3301](https://github.com/objectionary/eo/issues/3301).

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#3300](https://github.com/objectionary/eo/issues/3300) is still not solved; solved: [#3298](https://github.com/objectionary/eo/issues/3298), [#3299](https://github.com/objectionary/eo/issues/3299), [#3301](https://github.com/objectionary/eo/issues/3301).
