### ISSUE TITLE
recursive implementation of the `tuple` is very inefficient

### ISSUE THREAD

**Issue by volodya-lombrozo** [objectionary/eo#3307]
I am facing a problem with printing PHI expressions. I encountered the following exception when I ran `eo-maven-plugin:0.39.0:xmir-to-phi`:

```java
[ERROR] #fatalError(): Too many nested function calls. May be due to infinite recursion; SystemID: file:///org/eolang/parser/set-locators.xsl; Line#: 43; Column#: 11
```

As you can see, the `set-locators.xsl` transformation uses too many nested function calls. This problem usually happens on Windows OS, and it's flaky. I have attached the full log below.

[build.log](https://github.com/user-attachments/files/16426689/build.log)

**Comment by volodya-lombrozo** [comment]
@yegor256 @maxonfjvipon Please, take a look. This problem happens rather often and it influence `xmir-to-phi` transformation. 

Examples: 
- https://github.com/objectionary/jeo-maven-plugin/actions/runs/10160476957 (windows)
- https://github.com/objectionary/jeo-maven-plugin/actions/runs/10160269045 (windows)
- https://github.com/objectionary/jeo-maven-plugin/actions/runs/10159421948 (ubuntu)

**Comment by yegor256** [comment]
@maxonfjvipon please, help us here

**Comment by volodya-lombrozo** [comment]
Blocks https://github.com/objectionary/jeo-maven-plugin/issues/645

**Comment by maxonfjvipon** [comment]
@volodya-lombrozo @yegor256  in the provided log processed XMIR is printed and it has 379 nested `tuple` objects. I think it's too much for us:
1. it's unreadable
2. we can't deal with it at the level of phi because it would be also unreadable
3. it causes such flaky tests

(Stars on line 314, ends on line 690)
<img width="1496" alt="image" src="https://github.com/user-attachments/assets/1ddc3683-5b9c-4109-827a-5e1016141fa5">
<img width="1496" alt="image" src="https://github.com/user-attachments/assets/80a852e8-75d2-427c-a5a0-d2ec3f439159">

I see two scenarios:
1. we're finding a way to configure XSLT engine (if it exists) and setting some parameter which is responsible for max nested calls. Transformations will work, it'll be still unreadable and may cause some other unknown problems in the future
2. we're making an exception and changing the structure of XMIR - instead of `tuple` we're using some mysterious atom which accepts unlimited amount of parameters. We'll use the atom only for jeo, opeo. So instead of:
```
tuple
  tuple
    tuple
      tuple
        tuple
          ...
             tuple
               tuple.empty
               1
             2
           ...
         300
       301
     302
   303
```

we'll get:
```
array
  1
  2
  3
  4
  ...
  302
  303
```

Since here we use EO and XMIR as IR - we don't need to run it, which means we can do it. The code's much more readable, does not contain so many nested object and should not cause unpredictable troubles related to large nesting.

WDYT?

**Comment by volodya-lombrozo** [comment]
@maxonfjvipon  To be honest, I like the both suggestions. However, adding "mysterious" atoms might cause some problems in the future as well. I would suggest to try the first point first, then if we don't find anything satisfiable (or it will take significant time,) we can just go by the second path. What do you think?
The first option seems a bit faster to solve. And I don't think we will have many of such long methods with ~> 300 instructions.

**Comment by volodya-lombrozo** [comment]
@maxonfjvipon Friendly reminder

**Comment by maxonfjvipon** [comment]
@volodya-lombrozo [here](https://saxonica.plan.io/boards/3/topics/3732) I found the info that such behaviour is related to insufficient stack size (which is 256M now).
Also we can try to optimize XSLs so they use tail recursion instead of head one.
So try to increase stack size for now via command line argument, it should help for now, and I'll check what I can do with tail recursion

**Comment by volodya-lombrozo** [comment]
@maxonfjvipon Thanks. I will try to increase stack size for now.

**Comment by yegor256** [comment]
@volodya-lombrozo I believe, it's fixed?

**Comment by volodya-lombrozo** [comment]
@yegor256 How? [The problem](https://github.com/objectionary/eo/issues/3307#issuecomment-2260197532) is still here, as far as I understand. @maxonfjvipon Please, correct me, if I'm wrong. If we have a `tuple` with many inner `tuples` inside we have a stackoverflow error. For now, I fixed it by increasing the stack size, but on your side there are no changes. Or I'm wrong?

**Comment by yegor256** [comment]
@maxonfjvipon we may think about a more optimal implementation of `tuple`, maybe via `tuple3`, `tuple4`, `tuple5`, and so on atoms?

**Comment by maxonfjvipon** [comment]
@yegor256 we definitely should

**Comment by yegor256** [comment]
@volodya-lombrozo still an issue? (we won't change the implementation of the `tuple`)

**Comment by volodya-lombrozo** [comment]
@yegor256 What about `tuple1`, `tuple2`, ... implementations? are you going to implement them?

https://github.com/objectionary/eo/issues/3307#issuecomment-2410650191

**Comment by yegor256** [comment]
@volodya-lombrozo no, we won't do this. Such a performance optimization may be reasonable when EO programs are fast but need to become a bit faster. Currently, the binaries that our compiler produces are very slow. By making them "a bit faster" we won't gain anything but will only lose the cleanness of the code and simplicity of implementation. Simply put, we will think about this much much later.

**Comment by volodya-lombrozo** [comment]
@yegor256 I see. Maybe we can mention this issue somewhere in the documentation then? I can do it, but I need to know where.

**Comment by yegor256** [comment]
@volodya-lombrozo I don't know either. There are plenty of places where we can improve EO objects. This ticket will easily be findable in the bug tracker later. I suggest we just close it.

**Comment by volodya-lombrozo** [comment]
Ok, let's close it
